ajolma/Geo-GDAL-FFI

lib/Geo/GDAL/FFI.pm
The others all compile and run.  They do need ```use 5.010``` to be added to the top of the scripts, but that's not really an issue I think.
=> Fix method name in synopsis

lib/Geo/GDAL/FFI/SpatialReference.pm
Otherwise we can get double frees if objects are shared.
Not sure if this will lead to memory leaks, but it avoids test failures in Biodiverse.  Let me know if there are better approaches.  
I also had a look at implementing the GetReferenceCount method for SpatialReference objects, but am not sure what the naming convention should be given it is not in any of the already processed header files.
=> SpatialReference destroy: Guard against ref count

lib/Geo/GDAL/FFI/Layer.pm, t/layer.t
Implemented as a wrapper around the Defn object
instead of dropping down to the GDAL API call.
My understanding is that the API follows the same
process, just at the API level.
=> Add GetName method to Layer.pm

lib/Geo/GDAL/FFI/Dataset.pm
This makes it easier for the casual user to find the relevant options.  
(It took me a while to realise that the rasterize options array was just a set of the command line switches.)
I was not sure of the exact usage for DEMProcessing as it has several modes.
Let me know if you prefer a different wording.
=> Add more details and links to the utility docs.

lib/Geo/GDAL/FFI/Dataset.pm, t/dataset_rasterize.t, t/rasterize_crash.t
Code adapted from https://github.com/ajolma/Geo-GDAL-FFI/issues/15#issuecomment-443414101 
The main difference is that it throws an exception when called in non-void context but a Destination argument is passed.  Failing loudly is probably better than returning undef and failing later when the return arg is used.
Also add a test for this behaviour.
If this looks good then I can do the same for the other utilities:
Warp
VectorTranslate
NearBlack
=> Rasterize and seg faults

lib/Geo/GDAL/FFI/Dataset.pm, t/layer.t
Adds Geo::GDAL::Dataset::ExecuteSQL method to support filters and build spatial indexes.  
Test is cursory at this stage.  
It probably needs work, as I'm not sure if the return value is correct.  The API lists a layer should be returned in several cases, but not all.  I'll modify based on suggestions.  
Remaining work (add to as needed):
=> ExecuteSQL method for Dataset.pm

lib/Geo/GDAL/FFI.pm
The package config files are not updated when packed, so point to the location the files have come from and not to the temporary directory the data are extracted to when run as a PAR archive.
When that happens, Geo::GDAL::FFI cannot find the gcs.csv file and will not run many of the processes.
=> Ensure the Alien::gdal data dir is found when packed using PAR::Packer

ci/without-gdal-dev.sh
Remove double handling of line aggregation so travis
sees progress and does not time out.
=> The Alien::gdal build handles long log lines under CI

.travis.yml, t/00.t
The changes to GDAL 3 and Proj 6 mean that gcs.csv not longer exists in the data dir, so update the tests to use a file that does.  
One test remains, and could be updated using by adding ```Alien::gdal->version ge '3'``` to the condition.  I can add that as well.
```perl
if (FindFile('gcs.csv') || Alien::gdal->version ge '3') {
@sr = (SpatialReference => Geo::GDAL::FFI::SpatialReference->new(EPSG => 3067));
}
```
=> data file tests: gcs.csv does not exist in GDAL 3

lib/Geo/GDAL/FFI.pm, lib/Geo/GDAL/FFI/Band.pm
PDL takes about 0.25 seconds of the startup time.
This adds up when running test suites with many files
for downstream dependencies like Biodiverse.
=> Import less of PDL at startup, and localise its imports

ci/with-gdal-dev.sh
GDAL 3.0 is needed for Alien::gdal since 1.18,
so the dev version now might not be sufficient
for a system install.
Mac builds for Alien::gdal use the system install, 
so could be an option instead.  This is under 
GitHub workflows, but should also be the case for Travis.
=> Travis: Verbose install on dev version

t/layer.t
Update layer.t to account for changes in Geos 3.9.  
Ideally we would also expose the Normalize function for geometries, but that's perhaps for later.  (Edit - raised in issue #44 )
=> Layer tests

.github/workflows/linux.yml, .github/workflows/linux_share_build.yml, .github/workflows/linux_sys_build.yml, .github/workflows/macos.yml, .github/workflows/macos_share_builds.yml, .github/workflows/windows.yml
~~The Linux system install seems to be getting libgdal-dev v2 instead of v3.  This build should be on Ubuntu 20.04 which has libgdal-dev 3.0.4 so I am not sure what is going on.~~
Edit - the minimum version supported by Alien::gdal is 3.1, so the Ubuntu default is currently too low.
The others also likely need work so treat this as draft for now.
=> Add CI configs for GitHub workflows

.github/workflows/linux_share_build.yml, .github/workflows/linux_sys_build.yml, .github/workflows/macos.yml, .github/workflows/macos_share_builds.yml, .github/workflows/windows.yml, Makefile.PL, lib/Geo/GDAL/FFI.pm
Updates #48 
The first commit also checks for a lib64 dir, although it is probably not needed when the second commit is in place.  
The last three commits update the CI actions and disable some debug code that is not always reliable because of lib64 dirs.  These should perhaps be squashed.
=> Only update the data dir if GDAL<=2.3.1

Changes, Makefile.PL, lib/Geo/GDAL/FFI/VSI/File.pm
As for [FFI::Platypus::Declare](https://metacpan.org/pod/FFI::Platypus::Declare), the use of this module (now extracted from FFI::Platypus) is officially discouraged/deprecated.
=> Removed use of now discouraged FFI::Platypus::Declare module.

lib/Geo/GDAL/FFI/Layer.pm, t/00.t, t/layer.t
=> Add Layer::GetFeatureCount method

lib/Geo/GDAL/FFI/VSI/File.pm
The lintian QA tool reported a spelling error for the Debian package build:
* succesfully -> successfully
=> Fix spelling errors.

t/vsistdout.t
=> t/vsistdout.t: return 1 on write success

.github/workflows/linux_bin_build.yml, .github/workflows/linux_share_build.yml, .github/workflows/linux_sys_build.yml, .github/workflows/macos.yml, .github/workflows/macos_share_builds.yml, Makefile.PL, t/00.t, t/dataset.t, t/dataset_rasterize.t, t/open.t
Fixes #61 
Will need to be rebased on #72 before it is merged.
=> Tests: use Test::TempDir::Tiny and Path::Tiny

build-tools/parse_h.pl, lib/Geo/GDAL/FFI.pm
This version of the  named script is fixed to correctly manage arrays instead of pointers when required (as manually fixed in PR #68  ). It is also updated to parse GDAL 3.9 headers, including the gdal_alg.h. That header is commented out in the script, which allows it to generate exactly the same code currently embedded in the master (for GDAL 3.7). I added some additional callback types, too.
=> Revised parse_h.pl script to parse GDAL headers up to v3.9
